FROM openjdk:21-jdk-slim

# Set up environment variables with defaults from build args
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_MAIL_USERNAME
ARG SPRING_MAIL_PASSWORD
ARG JWT_SECRET
ARG MPESA_AUTH_HEADER
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION

ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
ENV SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME
ENV SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD
ENV JWT_SECRET=$JWT_SECRET
ENV MPESA_AUTH_HEADER=$MPESA_AUTH_HEADER
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$AWS_REGION

# Update apt-get and install curl
RUN apt-get update && apt-get install -y curl

# Define a volume for temporary files
VOLUME /tmp

# Copy the JAR file built from Maven to the container
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

# Set entrypoint for running the Spring Boot application
ENTRYPOINT ["java", "-jar", "/app.jar"]
