services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: h$+4PrDpjVN!
      MYSQL_DATABASE: events_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "8080:9090"
    env_file:
      - .env

volumes:
  mysql_data:
