spring:
  datasource:
    url: jdbc:mysql://localhost:3306/events_db
    username: root
    password: h$+4PrDpjVN!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # or "create", "validate"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
